# Configuration file for re-command
# This file contains default values for local development
# In Docker, this file is generated by entrypoint.sh from environment variables

# Navidrome Configuration
ROOT_ND = ""
USER_ND = ""
PASSWORD_ND = ""
MUSIC_LIBRARY_PATH = "/path/to/music"
TEMP_DOWNLOAD_FOLDER = "/path/to/temp"

# ListenBrainz API Configuration
LISTENBRAINZ_ENABLED = False
ROOT_LB = "https://api.listenbrainz.org"
TOKEN_LB = ""
USER_LB = ""

# Last.fm API Configuration
LASTFM_ENABLED = False
LASTFM_API_KEY = ""
LASTFM_API_SECRET = ""
LASTFM_USERNAME = ""
LASTFM_PASSWORD_HASH = ""
LASTFM_SESSION_KEY = ""

# Deezer Configuration
DEEZER_ARL = ""

# Download Method
DOWNLOAD_METHOD = "streamrip"

# Comment Tags for Playlist Creation
TARGET_COMMENT = "lb_recommendation"
LASTFM_TARGET_COMMENT = "lastfm_recommendation"

# History Tracking
PLAYLIST_HISTORY_FILE = "playlist_history.txt"
