import os

ROOT_ND = os.getenv("RECOMMAND_ROOT_ND", "")
USER_ND = os.getenv("RECOMMAND_USER_ND", "")
PASSWORD_ND = os.getenv("RECOMMAND_PASSWORD_ND", "")
MUSIC_LIBRARY_PATH = os.getenv("RECOMMAND_MUSIC_LIBRARY_PATH", "/path/to/music")
TEMP_DOWNLOAD_FOLDER = os.getenv("RECOMMAND_TEMP_DOWNLOAD_FOLDER", "/tmp/temp_downloads")

ROOT_LB = os.getenv("RECOMMAND_ROOT_LB", "https://api.listenbrainz.org")
TOKEN_LB = os.getenv("RECOMMAND_TOKEN_LB", "")
USER_LB = os.getenv("RECOMMAND_USER_LB", "")
LISTENBRAINZ_ENABLED = os.getenv("RECOMMAND_LISTENBRAINZ_ENABLED", "False").lower() == "true"

LASTFM_ENABLED = os.getenv("RECOMMAND_LASTFM_ENABLED", "False").lower() == "true"
LASTFM_API_KEY = os.getenv("RECOMMAND_LASTFM_API_KEY", "")
LASTFM_API_SECRET = os.getenv("RECOMMAND_LASTFM_API_SECRET", "")
LASTFM_USERNAME = os.getenv("RECOMMAND_LASTFM_USERNAME", "")
LASTFM_PASSWORD = os.getenv("RECOMMAND_LASTFM_PASSWORD", "")
LASTFM_PASSWORD_HASH = os.getenv("RECOMMAND_LASTFM_PASSWORD_HASH", "")
LASTFM_SESSION_KEY = os.getenv("RECOMMAND_LASTFM_SESSION_KEY", "")
LASTFM_TARGET_COMMENT = os.getenv("RECOMMAND_LASTFM_TARGET_COMMENT", "lastfm_recommendation")

LLM_ENABLED = os.getenv("RECOMMAND_LLM_ENABLED", "False").lower() == "true"
LLM_PROVIDER = os.getenv("RECOMMAND_LLM_PROVIDER", "")
LLM_API_KEY = os.getenv("RECOMMAND_LLM_API_KEY", "")
LLM_MODEL_NAME = os.getenv("RECOMMAND_LLM_MODEL_NAME", "")
LLM_BASE_URL = os.getenv("RECOMMAND_LLM_BASE_URL", "")
LLM_TARGET_COMMENT = os.getenv("RECOMMAND_LLM_TARGET_COMMENT", "llm_recommendation")

DEEZER_ARL = os.getenv("RECOMMAND_DEEZER_ARL", "")
DOWNLOAD_METHOD = os.getenv("RECOMMAND_DOWNLOAD_METHOD", "streamrip")

ALBUM_RECOMMENDATION_ENABLED = os.getenv("RECOMMAND_ALBUM_RECOMMENDATION_ENABLED", "false").lower() == "true"
ALBUM_RECOMMENDATION_COMMENT = os.getenv("RECOMMAND_ALBUM_RECOMMENDATION_COMMENT", "album_recommendation")

HIDE_DOWNLOAD_FROM_LINK = os.getenv("RECOMMAND_HIDE_DOWNLOAD_FROM_LINK", "false").lower() == "true"
HIDE_FRESH_RELEASES = os.getenv("RECOMMAND_HIDE_FRESH_RELEASES", "false").lower() == "true"

TARGET_COMMENT = os.getenv("RECOMMAND_TARGET_COMMENT", "lb_recommendation")
PLAYLIST_HISTORY_FILE = os.getenv("RECOMMAND_PLAYLIST_HISTORY_FILE", "playlist_history.txt")
FRESH_RELEASES_CACHE_DURATION = int(os.getenv("RECOMMAND_FRESH_RELEASES_CACHE_DURATION", "300"))
FRESH_RELEASES_DAYS = int(os.getenv("RECOMMAND_FRESH_RELEASES_DAYS", "30"))
DEEZER_MAX_CONCURRENT_REQUESTS = int(os.getenv("RECOMMAND_DEEZER_MAX_CONCURRENT_REQUESTS", "3"))

LOCAL_DATA_DIR = os.path.dirname(os.path.abspath(__file__))
STREAMRIP_CONFIG_PATH = os.path.join(LOCAL_DATA_DIR, ".streamrip_config.toml")
